### ISSUE TITLE
Ability to load multiple CSS

### ISSUE THREAD

**Issue by shaggyze** [ValerioLyndon/Theme-Customiser#14]
**What is your desired feature/change?**
Ability to load multiple CSS.

**Why should this be added?**
So I can load the CSS mod and user URL import in a single mod toggle.

**Additional notes**
either like
```
		"synopsis": {
			"name": "Synopsis",
			"description": "Adds synopsis on hover",
			"css": {"bottom": "https://shaggyze.github.io/Themes/Mod%20-%20Synopsis.css"},
			"css": {"import": "@\\import \"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\";"},
			"options": {
				"import-url": {
				"name": "URL to your CSS",
				"type": "text",
				"replacements": [["\"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\"", "\"{{{insert}}}\""]],
				"default": "https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css"
				}
			}
		}
```
or
```
		"synopsis": {
			"name": "Synopsis",
			"description": "Adds synopsis on hover",
			"css": {"bottom": "https://shaggyze.github.io/Themes/Mod%20-%20Synopsis.css"},
			"css1": {"import": "@\\import \"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\";"},
			"options": {
				"import-url": {
				"name": "URL to your CSS",
				"type": "text",
				"replacements": [["\"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\"", "\"{{{insert}}}\""]],
				"default": "https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css"
				}
			}
		}
```
Edit:
This may be related to #13 but I posted this before seeing that one.

**Comment by ValerioLyndon** [comment]
This is mostly possible already by putting both keys in the same dictionary. For example:
```
"css": {
    "import": "@\\import \"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\";",
    "bottom": "https://shaggyze.github.io/Themes/Mod%20-%20Synopsis.css"
}
```

One of each key (`bottom`, `top`, and `import`) is allowed, with each having it's own CSS.

If you were wanting more than one per section, this could potentially be expanded to an infinite amount if we use arrays instead of dictionaries. That could be applied in a new commit without much trouble. Here's some example code.
```
"css": [
    ["import", "@\\import \"https://example.com/import1.css\";"],
    ["import", "@\\import \"https://example.com/import2.css\";"],
    ["bottom", ".code1 {}"],
    ["bottom", ".code2 {}"]
]
```
> This code is purely for demonstration and will not work.

**Comment by shaggyze** [comment]
Shit, should have thought about that or tried it.
First example worked as intended.

Not sure if arrays would ever be needed cause infinite is a lot, but if we ever need more than 3 we can come back to this.

**Comment by ValerioLyndon** [comment]
No worries lol, my code is messy and the wiki still needs a lot of work.
