### ISSUE TITLE
Split JSON into collection JSON and theme JSON.

### ISSUE THREAD

**Issue by ValerioLyndon** [ValerioLyndon/Theme-Customiser#15]
### **What is your desired feature/change?**
Theme JSON should be split. Specifically, I would recommend having two JSON types: 
- Theme JSON, for the customiser page. This JSON would be one theme per file as opposed to the current format
- Collection JSON, for the browse page. This JSON would contain basic theme info such as id, name, type, preview, and a link to the theme-specific JSON.

### **Why should this be added?**
This will have various benefits:
- Reduce amount of data loaded. If a user only visits one theme, they have no need for all the other themes' data.
- Prevent JSON errors from breaking all themes.
- Allow much larger collection files that span multiple theme authors' works. As it is now, if you were to load, say, 50 themes multiple of which have complex mods, it would probably be about 1MB of data. A collection JSON would be tiny as it would not have mod or option data.

### **Additional notes**
The downsides would be more network requests and slightly more data overall since both the collection and theme JSON files would have to contain basic such as name and type etc. More data would be **if** and only if you visited every theme. If you visit only one theme it will still be less.

There is also the slight problem of potential name or author mismatches, but I consider this a minor issue.

If you go ahead with this then you could implement theme JSON one of two ways:
- Keep the format the same. but simply ignore subsequent theme keys.
- Or, flatten the JSON and add an "id" key to the theme. This would break all older JSON though and I don't see much point to it unless you want to force this change.

The URL parameters would also have to be changed. If JSON is theme-specific, you could potentially remove the theme ID entirely and simply replace it with a URL to the JSON. But this would make it harder to identify the theme during imports. Either way, you could have the theme param as either `?data=` or `?theme=` and the collection could be `?c=` or `?collection=`.

This would probably be a good time to implement a "version" key to the JSON file and process different JSON versions as appropriate. That said, it would have to eventually be removed to keep things lightweight and I believe the only person using this other than me right now is Shaggy.

**Comment by ValerioLyndon** [comment]
**Opinions welcome.** I've been brainstorming this for a couple of days and I believe it may be the best way forwards before the JSON format is set in stone, but I don't want to go ahead until I'm more sure.

**Comment by shaggyze** [comment]
This also crossed my mind when you added the browser page and I noticed customiser.json and shared.json having all the mods options. personally, I've been making a ton of JSON syntax mistakes even with just a single theme in data.json lol so I think this is a good idea.
