### ISSUE TITLE
Dropdown menu for view as

### ISSUE THREAD

**Issue by shaggyze** [ValerioLyndon/Theme-Customiser#25]
**What is your desired feature/change?**
A dropdown menu on the preview page for Owner, Guest or Logged off instead of always being data-owner="1"

**Why should this be added?**
So theme creators can preview what guests or logged-off viewers see.

**Comment by ValerioLyndon** [comment]
Great suggestion! I don't think this should be too difficult, just need to put aside the time to do it.

Perhaps I could add a toggle for the cover image while I'm at it... mostly noting that for myself so I don't forget.
