### ISSUE TITLE
New JSON type: collection of collections.

### ISSUE THREAD

**Issue by ValerioLyndon** [ValerioLyndon/Theme-Customiser#27]
### **What is your desired feature/change?**

A new JSON type that links to various collection JSONs. Would act as a simple referral to the linked collection URLs same as URL parameters function now.

### **Why should this be added?**

1. The URL would be a lot simpler. Rather than having multiple URLs with `c=URL&c=URL&c=URL`, so on, so on, it would simply be `cc=URL`.
2. If you want to add a new collection JSON to the commonly shared pages, there would no longer be any need to change every GitHub reference, forum post, or other resource.

### **Additional notes**

I am not a *huge* fan of this idea, as it means even more HTTP requests, more data to load, more JSON to be kept up-to-date, but I think the benefits are enough that it's worth mentioning.

The URL parameter could be `cc` for "collection of collections"/"combined collections", `m` for "mega collection", or something similar.
```
...github.io/Theme-Customiser/?cc=https://example.com/collections.json
```

The format would probably be something like this:
```
{
  "json_version": 0.2,
  "collections": [
    "https://example.com/myCollection.json",
    "https://example.com/mySecondCollection.json"
  ]
}
```

**Comment by shaggyze** [comment]
I like this idea since the URL will be shorter for when multiple collections are submitted/added.
