### ISSUE TITLE
[BUG] replacements not working?

### ISSUE THREAD

**Issue by shaggyze** [ValerioLyndon/Theme-Customiser#30]
not sure when this started happening but changing any replacement value banner, background etc isn't working anymore 
results in:
```
--banner-avatar: --banner-avatar: {{{insert}}};
--background: --background: {{{insert}}};
--banner: --banner: {{{insert}}};
```

**Comment by ValerioLyndon** [comment]
Seems to have been a simple typo on a variable. >_> Not sure how I missed it considering I was testing this during development and it was working up to a point... Oh well, thanks for pointing this out. It should (hopefully) be fixed now.
