### ISSUE TITLE
[BUG] Preview looks fine, but transparency seems to be borked in the actual MyAnimeList view.

### ISSUE THREAD

**Issue by muuyo** [ValerioLyndon/Theme-Customiser#33]
**Describe the bug**

Transparency seems fine in the preview on the Style Customizer, with transparent rows and everything looking fine, however when viewing it on the real site transparency is broken and it's simply gray - interestingly, the intended background image shows only within the rows.

**To Reproduce**

View what the settings would produce in the Style Customizer preview, then view what the CSS applied on MyAnimelist looks like.

**Screenshots**

![image](https://user-images.githubusercontent.com/34991771/184477171-5fbbadf7-962a-4c8f-b496-77b443b209fa.png)
![image](https://user-images.githubusercontent.com/34991771/184477178-7a760005-71fa-4b0a-8f76-8bee11044bc0.png)

**Desktop (please complete the following information):**

 - Operating System: Windows
 - Browser Firefox
 - Version 103.02

Exported Settings below.

`{"data":"https://valeriolyndon.github.io/MAL-Public-List-Designs/Clarity Theme/clarity.json","options":{"avatar":"https://cdn.myanimelist.net/images/userimages/7275386.jpg","banner":"https://i.imgur.com/w2eG4i3.jpg","character":"https://i.imgur.com/ssqJxad.png","background":"https://i.imgur.com/K8wo1zs.png"},"mods":{"dark":{},"review":{},"banner-height":{"height":"450px"},"fav":{"align":"left"},"render":{"left-size":"","left-img":"https://i.imgur.com/Xd5d4c7.png"},"header-line":{"colour":"#2787F6"},"status-width":{"width":"4px"},"transparent-rows":{"colour":"rgba(1,4,7,.7)"}},"theme":"Clarity"}`

**Comment by ValerioLyndon** [comment]
Hi there, thanks for the bug report!

Unfortunately I seem to be unable to reproduce the issue. Previews look fine and your list seems to be fine when I view it at https://myanimelist.net/animelist/muuyo
![22-08-13 09;46;36 firefox 3840x1080 - 08208](https://user-images.githubusercontent.com/29792052/184503492-84f85a95-60a6-42b0-a126-d0e6dbbe383a.png)

Could you confirm a couple of things for me.
1. Does your list look fine once you view it outside of the preview? At https://myanimelist.net/animelist/muuyo
2. Do you have any browser extensions, especially uBlock Origin?
3. If you do, does the issue still occur with the extensions temporarily disabled?

**Comment by muuyo** [comment]
I'm an idiot, no worries. It seems my dark mode extension, that I specifically disabled on the site then installed an alternative for, breaks it. No. 2 got me to look at my extensions, so that was it! Thanks!

**Comment by ValerioLyndon** [comment]
It happens lol, I've been there. Glad it's fixed!
