### ISSUE TITLE
Implement colour picker directly into page

### ISSUE THREAD

**Issue by ValerioLyndon** [ValerioLyndon/Theme-Customiser#40]
The "color" option type should provide a colour picker on the actual customiser page instead of directing users to another website. This provides obvious usability improvements.

The only trouble is I have no idea how to code one so will have to find a free library or something.

There is obviously the built-in browser colour picker but it sucks so we aren't going to use that so don't mention it.

**Comment by shaggyze** [comment]
dude, I was going to mention this like a month ago, I have no issues with the built-in browser color picker, but yea if you can find a free library that's better then that's just as good as long as it has the same options or more.
