### ISSUE TITLE
[BUG] Animes pictures do not load 

### ISSUE THREAD

**Issue by Kmeuh** [ValerioLyndon/Theme-Customiser#44]
**Describe the bug**

My anime list is full of black poster. 

**Desktop**

 - Operating System: Windows 10
 - Browser: Edge
 - Version: 104
 - Notable browser extensions: uBlock origin, AdGuard, Dark Reader

**Screenshots**

![image](https://user-images.githubusercontent.com/4040117/188690656-1442b590-b21a-401e-9116-5d2577d593c1.png)

![image](https://user-images.githubusercontent.com/4040117/188691125-a15074c5-fe6a-4075-8ae7-b05718c12d2b.png)

**Customiser Settings**

```
{"data":"https://valeriolyndon.github.io/MAL-Public-List-Designs/Brink Theme/brink.json","options":{"--imageBrightness":"100","--imagebrightnessHov":"80","--imageBlurHov":"2.00","--infoBGOpacity":"85","--bannerVignetteOpacity":"0","--toggleStats":true},"mods":{"cat-images":{"1c":"https://i.imgur.com/0mJ1T0T.jpg","7c":"https://i.imgur.com/9hPj7wa.png","2c":"https://i.imgur.com/I6jnvBP.jpg","3c":"https://i.imgur.com/SVFsnWh.jpg","6c":"https://i.imgur.com/ixkWzjk.jpg","4c":"https://i.imgur.com/fss4OPG.jpg"},"cat-info":{}},"theme":"Brink"}
```

**Additional context**

Tested with uBlock / AdGuard / Dark Reader disabled.

**Comment by ValerioLyndon** [comment]
Did you enable the Images column in your [list settings](https://myanimelist.net/editprofile.php?go=listpreferences), as specified in the recommended configuration?

If you did, reload the preview page to refresh its settings. If the problem still occurs, a link to your publicly available anime or mangalist with the design applied would help a lot. I did test on Edge and Firefox to be sure and my list looks fine with the Image column enabled.

**Comment by Kmeuh** [comment]
I'm an idiot.

It works with the option checked, thank you ahah.

**Comment by ValerioLyndon** [comment]
Not a problem. We've all been there, thanks for the details in the report!
