### ISSUE TITLE
[BUG] Clarified By Valerio Lyndon "Character Renders" Not Working

### ISSUE THREAD

**Issue by Shafkathasan** [ValerioLyndon/Theme-Customiser#46]
Character Renders isn't Working.
I change "Character Renders" links but links don't change on CSS.
https://imgur.com/a/k9P70fQ

**Comment by ValerioLyndon** [comment]
Ah, this was due to a Render update I pushed just yesterday. Accidentally buggered a couple of the settings in the process. If you try again it should work fine.

Thanks for the bug report!
