### ISSUE TITLE
Allow fetching URL in replacement CSS

### ISSUE THREAD

**Issue by ValerioLyndon** [ValerioLyndon/Theme-Customiser#7]
**What is your desired feature/change?**
Allow fetching a URL resource for CSS in options the same way that mods and the theme do currently.

**Why should this be added?**
This would make it a lot easier to add selections and toggles for the entire mod's CSS.

**Additional notes**
It could also be argued that this shouldn't be added in favour of allowing variants for mod and option CSS.

**Comment by shaggyze** [comment]
not sure if this is the same issue or not, but it would be nice to have an option or mod to add @\import "{{{insert}}}"; to the top as well with a subtype called import_url for instance
`"css": {"top": "https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css"}`
the above in theory might work but is too much data due to MAL CSS limits anyway.

Edit:
actually doesn't look like the above works either, it's probably too much data for "css" too
https://valeriolyndon.github.io/Theme-Customiser/?theme=mytheme&data=https://shaggyze.github.io/Themes/ZeroEffort/data.json

**Comment by ValerioLyndon** [comment]
> it would be nice to have an option or mod to add @\import "{{{insert}}}"; to the top

You could do this manually by inputting the import code i.e: `"css": {"top": "@\\import \"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\";"}`. There is also the "import" placement for css which should places the line directly below any other imports, which should help with CSS priority and ordering. `"css": {"import": "@\\import \"https://dl.dropboxusercontent.com/s/ta5rab8nycn6950/maltags.css\";"}`
For a full example of a mod with a user-insertable import link:
```
"test": {
	"name": "Test Import",
	"css": {"import": "@\\import \"\";"},
	"options": {
		"test-url": {
			"name": "URL to your CSS",
			"type": "text",
			"replacements": [["\"\"", "\"{{{insert}}}\""]]
		}
	}
}
```
This definitely could be prettier though, for sure. And I take it you meant it would be nice to have an easier option for adding import codes? There could definitely be a subtype to help validate URLs or a main type which could add the import wrapping I suppose. Not entirely sure how much value it would add but it could be done I reckon.

> not sure if this is the same issue or not

This issue is more to do with directly fetching/grabbing the linked code and using it directly, rather than placing it in an @\import statement. Same as how the theme CSS and mod CSS are grabbed and used. It could be useful in replacements as well especially for toggles or select options that change a lot of code, but I am not convinced yet that it's worth adding instead of simply having the CSS in the JSON. But I also don't know that there is enough of a reason against, so I might add it anyway. Still pondering.

**Comment by shaggyze** [comment]
oh okay, yeah that's what I was looking for. thanks!
using your third example it looks like it just adds `@\import "";` but that could be related to bug #3
